### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by martin-hoger** [runspired/smoke-and-mirrors#158]
The addon looks exactly like what I need. But I am getting after starting the server:
```
TypeError: Cannot read property 'apply' of undefined
    at Class.module.exports.treeForApp (/data/node_modules/smoke-and-mirrors/index.js:86:38)
    at Class._treeFor (/data/node_modules/ember-cli/lib/models/addon.js:319:31)
    at Class.treeFor (/data/node_modules/ember-cli/lib/models/addon.js:289:19)
    at /data/node_modules/ember-cli/lib/broccoli/ember-app.js:371:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/data/node_modules/ember-cli/lib/broccoli/ember-app.js:369:30)
    at EmberApp._processedAppTree (/data/node_modules/ember-cli/lib/broccoli/ember-app.js:631:25)
    at EmberApp.appAndDependencies (/data/node_modules/ember-cli/lib/broccoli/ember-app.js:916:10)
    at EmberApp.javascript (/data/node_modules/ember-cli/lib/broccoli/ember-app.js:1031:34)
    at EmberApp.toArray (/data/node_modules/ember-cli/lib/broccoli/ember-app.js:1389:10)
```

I am running Ember 2.12.0.

**Comment by pzuraq** [comment]
This addon is currently being split out into a set of smaller individual addons on the `html-next` org. The `vertical-collection` component is at 1.0.0-beta.1 right now: https://github.com/html-next/vertical-collection

Maintenance on this repo is on the backburner for now, we'll be revisiting it once the individual components are done (this repo will just pull the components back in). PRs are welcome, but we aren't sure when we'll have time to review.

**Comment by bloodknight2010** [comment]
Me too. I got that error.How to solve?Pls help me.

**Comment by pzuraq** [comment]
@bloodknight2010 check out the alternate repo I posted above, vertical-collection is now in Beta 2 and getting much more stable.

**Comment by runspired** [comment]
Should be fixed by updating to `@html-next/vertical-collection` (now re-exported by this lib)
