### ISSUE TITLE
Issues in 0.3.3

### ISSUE THREAD

**Issue by aquamme** [runspired/smoke-and-mirrors#44]
* `idForFirstItem` isn't working - it always starts at the top of the list
* `firstReached` doesn't trigger upon initialization
* scroll position is not maintained during prepend
* An error occurs while scrolling - I assume it's related to some of these issues:

TypeError: Cannot read property 'shift' of undefined
    at adjustPositions (http://localhost:4200/assets/vendor.js:86881:22)
    at resize (http://localhost:4200/assets/vendor.js:86830:22)
    at _updateHeight (http://localhost:4200/assets/vendor.js:85109:35)
    at _ov_obscure (http://localhost:4200/assets/vendor.js:85125:12)
    at _setState (http://localhost:4200/assets/vendor.js:85057:40)
    at cull (http://localhost:4200/assets/vendor.js:85034:12)
    at http://localhost:4200/assets/vendor.js:84355:11
    at Array.forEach (native)
    at _removeComponents (http://localhost:4200/assets/vendor.js:84354:14)
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:10767:25)

**Comment by runspired** [comment]
The `firstReached` behavior change is intentional and will be documented. It only triggers during an upwards scroll.  `lastReached` now only triggers during a downwards scroll.

A new action hook will be made available for loading above or below on initialization in 0.3.4: tentatively called `collectionDidMount`.  The action will receive information about the first and last rendered items, including their index.

`idForFirstItem` has been fixed on master, a 0.3.4 release will be coming soon.
